### ISSUE TITLE
Is there a timer that sets the minimum close door delay?

### ISSUE THREAD

**Issue by xanderphillips** [aderusha/MQTTCarPresence#32] opened 2023-12-27 19:57 UTC
I skimmed the .ino code as well as the yaml file and don't see a close delay programmed into the logic.

For my setup the processing time of the MQTT messages seems to result in about a 1.5 min lag, which is pretty good, but wanted to know if there was a setting somewhere I didn't see that would allow extending it for people that wanted a longer window of time.

**Comment by aderusha** [comment] 2023-12-27 20:24
duplicate of https://github.com/aderusha/MQTTCarPresence/issues/31

**Closed as completed by aderusha** 2023-12-27 20:24 UTC
